window.MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      macros: {
        reals: "\\mathbb{R}",
        inner: ["\\left\\langle #1, #2 \\right\\rangle", 2],
        smallinner: ["\\langle #1, #2 \\rangle", 2],
        calM: "\\mathcal{M}",
        calN: "\\mathcal{N}",
        SOd: "\\mathrm{SO}(d)",
        T: "\\mathrm{T}",
        skeww: "\\mathrm{skew}",
        symm: "\\mathrm{sym}",
        Sym: "\\mathrm{Sym}",
        Proj: "\\mathrm{Proj}",
        grad: "\\mathrm{grad}",
        Hess: "\\mathrm{Hess}",
        Retr: "\\mathrm{R}",
        D: "\\mathrm{D}",
        Sd: "\\mathbb{S}^{d-1}",
        Rd: "\\mathbb{R}^{d}",
        Rk: "\\mathbb{R}^{k}",
        calE: "\\mathcal{E}",
        Stnp: "\\mathrm{St}(n,p)",
        Rnp: "\\mathbb{R}^{n \\times p}",
        Rnn: "\\mathbb{R}^{n \\times n}",
        Rn: "\\mathbb{R}^{n}",
        Sn: "\\mathbb{S}^{n}",
        Sm: "\\mathbb{S}^{m}",
        trace: "\\mathrm{Tr}",
        Trace: "\\mathrm{Tr}",
        diag: "\\mathrm{diag}",
        SOn: "\\mathrm{SO}(n)",
        rank: "\\mathrm{rank}",
        frakX: "\\mathfrak{X}",
        frakF: "\\mathfrak{F}",
        One: "\\mathbf{1}",
        dist: "\\mathrm{dist}",
        calP: "\\mathcal{P}",
        Rdd: "\\mathbb{R}^{d \\times d}",
        calU: "\\mathcal{U}",
        calV: "\\mathcal{V}",
        calW: "\\mathcal{W}",
        bigger: "<"
      }
    },
    svg: {
      fontCache: 'global'
    }
  };
